WHITESPACE = _{ " " | "\t" | "\n" }

identifier = @{ (ASCII_ALPHA | "_") ~ (ASCII_ALPHANUMERIC | "_")* }

variable = @{ identifier }
predicate = @{ identifier ~ "(" ~ (variable ~ ("," ~ variable)*)? ~ ")" }

primary = { predicate | variable | "(" ~ equivalence ~ ")" | quantifier }

not = { "NOT" ~ primary | primary }
and = { not ~ ("AND" ~ not)* }
or = { and ~ ("OR" ~ and)* }
implication = { or ~ ("->" ~ implication)? }
equivalence = { implication ~ ("<->" ~ equivalence)? }

quantifier = { ("∀" | "∃") ~ variable ~ primary }

program = { SOI ~ equivalence ~ EOI }

