WHITESPACE = _{ " " | "\t" | "\n" }

identifier = @{ (ASCII_ALPHA | "_") ~ (ASCII_ALPHANUMERIC | "_")* }

variable = @{ identifier }
predicate = @{ identifier ~ "(" ~ (variable ~ ("," ~ variable)*)? ~ ")" }

primary = { predicate | variable | "(" ~ equivalence ~ ")" | quantifier }

not = { "NOT" ~ primary | primary }
and = { not ~ ("AND" ~ not)* }
xor = { and ~ ("XOR" ~ and)* }
xand = { xor ~ ("XAND" ~ xor)* }
nand = { xand ~ ("NAND" ~ xand)* }
nor = { nand ~ ("NOR" ~ nand)* }
or = { nor ~ ("OR" ~ nor)* }
implication = { or ~ ("->" ~ implication)? }
equivalence = { implication ~ ("<->" ~ equivalence)? }

quantifier = { ("∀" | "∃") ~ variable ~ primary }

program = { SOI ~ equivalence ~ EOI }

